### ISSUE TITLE
Remove GitBook {% raw %}...{% endraw %} crutches

### ISSUE THREAD

**Issue by shaib** [DjangoGirls/tutorial-extensions#156]
In the past, this tutorial was rendered with GitBook.
This is now being changed to Honkit (the JS changes to support this have already [been committed](#153)).

With GitBook, inline code snippets needed to be surrounded by `{% raw %}` ... `{% endraw %}`, and so these tags are in current texts.

With Honkit, they need not to be, and if they are, the `{% raw %}` and `{% endraw %}` tags end up rendered into the page.

**Comment by das-g** [comment]
I'm pretty sure `{% raw %}` and `{% endraw %}` are sometimes also needed in HonKit, as we also use them in the main Django Girls tutorial, which has been using HonKit instead of GitBook for quite some time now. Maybe the cases where they are or aren't needed are subtly different between GitBook and HonKit?

**Comment by shaib** [comment]
Is it possible that Honkit is only used for local development? In the file I am working on (`homework/README.md`) every single one of them was rendered.

**Comment by spignelon** [comment]
For reference:

![image](https://github.com/DjangoGirls/tutorial-extensions/assets/92091338/e1b11673-0ccf-4e8d-99a2-1d07dc9058d3)

**Comment by das-g** [comment]
Seem like the difference is whether the `{% raw %}` and `{% endraw %}` template tags occur inside or outside of ``` `…` ``` backquotes. See #169 for a partial and #170 for a complete fix.
