### ISSUE TITLE
Issue at Improving the layout - 

### ISSUE THREAD

**Issue by amnocas** [DjangoGirls/tutorial-extensions#73]
At the section of this tutorial it is mentioned that:
"So now we have made sure that only authorized users (ie. us) can add, edit or publish posts. But everyone still gets to view the buttons to add or edit posts. " However I believe that is not true, if you are not authorized you cannot see it  because:

   {% if user.is_authenticated %}
            <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <a href="{% url 'post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
        {% else %}

I tried and I do not see those buttons... can you please check that this is the intended behavior?

Best and congratulations this is the best tutorial I've seen on django!

Ana

**Comment by sagayev** [comment]
You are partially right. On main page, everyone cannot see these buttons. But however if you copy the link(<mysite>/post/new/ in my case http://sagayev.pythonanywhere.com/post/new/) and paste into an incognito window you will be able access those pages.
However you will not be able to add new post. Because "a user" is needed.
I also think this part of the tutorial should be clarified.

**Comment by aniav** [comment]
This section of the tutorial was updated in the meantime and it now displays proper information. Thank you! 🌷
